Vagrant.configure("2") do |c|
  c.berkshelf.enabled = false if Vagrant.has_plugin?("vagrant-berkshelf")
  c.vm.box = "bento/ubuntu-14.04"
  c.vm.hostname = "default-ubuntu-1404"
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.synced_folder "/Users/jjasghar/repo/appengine_hello_world", "/tmp/repo-data", nil
  c.vm.provider :virtualbox do |p|
  end
end
